blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions & Support
    url: https://github.com/magnus919/n8n-nodes-shlink-ai/discussions/categories/q-a
    about: Ask questions and get support from the community
  - name: 💡 Feature Ideas
    url: https://github.com/magnus919/n8n-nodes-shlink-ai/discussions/categories/ideas
    about: Share and discuss new feature ideas
  - name: 📖 n8n Documentation
    url: https://docs.n8n.io/
    about: Official n8n documentation and guides